#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : home-assistant-frontend
Version  : 20210226.0
Release  : 187
URL      : https://files.pythonhosted.org/packages/80/f7/2177482648d9916b4cbf6e9c61e4059b2823177a8300e78f93fc3450535b/home-assistant-frontend-20210226.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/80/f7/2177482648d9916b4cbf6e9c61e4059b2823177a8300e78f93fc3450535b/home-assistant-frontend-20210226.0.tar.gz
Summary  : The Home Assistant frontend
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: home-assistant-frontend-license = %{version}-%{release}
Requires: home-assistant-frontend-python = %{version}-%{release}
Requires: home-assistant-frontend-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Home Assistant Frontend
This is the repository for the official [Home Assistant](https://home-assistant.io) frontend.

%package license
Summary: license components for the home-assistant-frontend package.
Group: Default

%description license
license components for the home-assistant-frontend package.


%package python
Summary: python components for the home-assistant-frontend package.
Group: Default
Requires: home-assistant-frontend-python3 = %{version}-%{release}

%description python
python components for the home-assistant-frontend package.


%package python3
Summary: python3 components for the home-assistant-frontend package.
Group: Default
Requires: python3-core
Provides: pypi(home_assistant_frontend)

%description python3
python3 components for the home-assistant-frontend package.


%prep
%setup -q -n home-assistant-frontend-20210226.0
cd %{_builddir}/home-assistant-frontend-20210226.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614611514
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/home-assistant-frontend
cp %{_builddir}/home-assistant-frontend-20210226.0/LICENSE.md %{buildroot}/usr/share/package-licenses/home-assistant-frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/authorize.ba9486ab.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/7d0116083cabbccafb66a7dc1b7850c35cb691f7
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.00ac850d160ffd776aa6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.02da7511bce80321dea5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc3f40e6ed8bcbf1f353f2820b6f6de1b60692aa
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.030123df0e9e71107030.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/8221af1259a5d2d0f00c62f1fc77fe1d97a1e2fe
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.04c386e5657233788a21.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.05704de642c3fd5d084c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.05a56822f96252bcfcd8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.05b54e40f1099f4ea772.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.09d2cfb037a3fa984a36.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.09d6438bb774f8e6e42b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.0c40726c712a22acd0de.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.0c6f526c2f54550c3ef0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.0df775d5b6efe6d9ee3e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.14a94d3b0983ca3856f6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.178ce3cb480f71920f35.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.1af07fd8cd6a4655b3a0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.24602abfff42cd1c18b7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.24bf8a715d6b4a037add.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.266796d0deea7f61f422.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.28655b2346aaccfa46fa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.2927d674cea9cf3502cf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/53304ea17e1aec59135e38fb41046b29226ee4c4
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.29603a0e222ecda80e5b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.2afb2dbab74d3dd6904f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.2ced088fc92661b8dc4b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.2d29c77700a3e4649689.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/dc3e013cd0b737daef34779bfdae382ea163d175
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.2d3dd76fb4b379fcd1d0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.3063ec79493a50983b59.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/8221af1259a5d2d0f00c62f1fc77fe1d97a1e2fe
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.35a09ba6697da18d50e3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.36758dc99134c9b63a69.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.375f19fb63d75af47c3b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.3803d2f6e071b1c437e7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.43a998f339906e0785b4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.44b320cde318d86f61b7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.4596827df2396e9a7f8a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.45af01b73e2f110c6cd2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.4945e107eed4436f72fc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.4bd558a6ff50577817e3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/56d4bbd6d09030f63728cd0c0ca3e4f5cc675ae1
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.4cb068c58556583ef75e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.4ea398f621f3db712186.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.4f7de6b28c33f47aeb7e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.51607d79e6f1ccf7ca1d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.52122d41eac2e98883f6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.524ffc682276ce693cb2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.528fea9bb83e08d1c00f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.53bdce84a145840eff75.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/52b17ec5e6f6b2e1b929a94e0bd82be968697e4d
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.5435263b972ec8fb7bc5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.57a0a6486f6b2f685c8c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ede281ca359aa558c7cc1f9cda6ed8d4155f916b
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.5a57414babfe9fc84a09.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d099fd87e78ef1309517326310d9deca839a4822
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.5baf1b01114162daa69b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.5d13e36a4854adf5ca1a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.5ea4c58e36995ca1ee3a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.5f3aa838dc9b2d08ac49.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.602efaeaec180677e476.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.61c6d16b4872a2c2e1eb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.61e48187036c8b45b38d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.683e7c8d38ceea6c3a8e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.69f4f661473dca324110.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.6c5c9b5b34b3007b05c3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.6dc5c4bf8d69b38b88ee.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.6f55440357e696e2a88d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.70142e7035e64303e5f3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.7215210eb405936bf0a0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.72b93d0227b0f0b9bce8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.7649499a5062a09974f5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.76eb93f03d118ae92d30.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.77975d727e7c29a8bebb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.788d0cbf59e8f3100cf2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.79b24402c73a68a42e48.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.7a98f98615ffb640341c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/52b17ec5e6f6b2e1b929a94e0bd82be968697e4d
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.7d7aa9f73ff445f050df.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.7dbe19eede6557ca7d5b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.801e81a5a3d8b867073e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.806ab456cff322d0c4bf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.8240b42df530abb81997.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.83f859cce4cf38c86030.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.857d620588193ac1da74.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/69b762f663d6f84e74531b04958db753995d73bc
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.884ac8c5bee0360fcd5c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.89fcb9094b03182dfead.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.8d62440b0b786170a61c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.8e06b8536ebe8f568c99.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.8fefe58e25ba24ba17f4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.8ff94393fc0cdbcbaa40.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.90925ce2a63fedd8bec3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.924988c50ed2134585e0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.92dbb7bc4b1f941a0f19.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.9596ad2eb4f10617820c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/5f5ceb3bcca2d04378e9be079c358c4df55dd279
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.95e89d8779b7da690e91.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.969a427448d8d1879f3b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.973af700e82b8ececd7e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.992fad2e8eb0f451068b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.9a885499f062b531f87d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.9b64073750d2dbb38717.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ea68a5af689f6c5b7deb26c906d794cc21b30c5d
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.9f4995f0100ed2ed8464.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.a267674f134756e85c26.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.a35f548bd032a2f21c59.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.a361b76350bc233da2f4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.a55e8f238c749603b0f5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.a5b2687d112658eb0656.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.a65f575e7a48bbc1228c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.a8a8c1318d0d4c1267b6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.a9980832645535ddbbd3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.aaa0d98c36f38c6a7929.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.aaaf73935d4770b14253.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.ac4fe4faa8a393b9198f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.ac4ff8ee86acf2d6ebc6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/e52de0b21ae90ae1a028c6551c36eadba3ae7c88
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.ad0a8a03f6f61cb80c7d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.af5f3b4dac26f1094a66.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/69870830409c8dc4d7516131e195dfd5a0ad7b5c
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.afe9547bf40ea2891df7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.b70fffc82585f79da96e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.b85dbfbb887db3d2db9f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.bcd2737fd3319f7ef40d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.bd3f79c3fd3db45e8a1b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.be136876c54ff136dbbb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.c566b82f937ded3159b9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.caea3db04289a7df4fc4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.cb581e6bc826dc241e13.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.d1b0620b0bbad40fef8a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.d42794729e92b1600385.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.d9b41c7c6dfd0cee6ef6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.db1dc343c67d69e7504f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.dba205b2cbd1a9d7f4d1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.de0232dddd81e67749a3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bdfd476700d49e8a2039d45efb2a07fc1ca66016
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.dea783001eae9fe7ea62.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3e99fe4555b051b96603c274976496d7262b4ca1
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.e1032f70772f9d5ad8e3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.e64664f1c4d63c68d7be.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.e676e0d085da678c52de.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3a5e42877be32c2f355e3d5d12f6e9744b02634d
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.e6d334571b62e51bb99c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.e750b0b53754f9bd5411.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.ea2f0070f75605dd2969.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.ea4f5c2754e3584da676.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.ea86f4e1790c34dda1bc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.ec26de33b174e94223aa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.ecd7c8fb477a20ff2336.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.eebff2edebdd8c1339f8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.eff8f5e0816d35f9992e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.f3bca60f7a72e4e0b653.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.f4f20e35c25a3a70618f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.f5588153b29f78bfaf24.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.f6678155518ac40039fb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.f8527762a08f2834fd89.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.f8d38d3750f6e21c0f03.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.f9c92127ecdf04b04722.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.f9f1a17ba8cb2afac29a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.fb8e19a8548a10635ab3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/chunk.fd8553ff2d513c3dcc76.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_es5/onboarding.ca7bbb0e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/25e294a6a0b71f82276a1f5a59dd5419091d78d7
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/app.c6ae8c21.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/1c03cb1c44bce8c770cf95f29b419b2f66b3f1e5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/authorize.c0c25e83.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/6c2db91439b31a6213936efdcdc0cac714289755
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.003648bcef57f252dd1e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.00c585e506ae0ba79d2f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.024bfaa24d270ae9851f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.0309d476e91e7e51050e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.04cd78c1fa2d15083471.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.061587d7d7cc494f0eb2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/22ad76b604b952863b489212cd4bd483934a0f91
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.067e3f236918f1b699bc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/abcdbb59740145f8df008f10b6786ec816877d8b
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.0730ca2a71e7deb368f3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.07c979b30443fc9b45c8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.08012c8d029e59f82858.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.0be7f0c0e6d2d7aa73a5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.0d2c11e84a7371c92cc3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/435d3db816faac614d5584fc8df6d09ea9828b3a
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.0dd22a43912196eb4a8c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.113ec7c558804764c210.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.12fbb23352ad0debe4d7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.13fa46861cf1c96cde12.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.14b801f30561d4b1e099.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.14d656861adb14009609.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bdfd476700d49e8a2039d45efb2a07fc1ca66016
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.15368d4ecdb08476ca97.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.159330ca6ae882ba26bd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.18981005644d518aa963.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.1c5448b671cc3ad0f611.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.1d02ff9964f9043f3ffd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.1ec06c5c2fdd744a85e6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.202d7ad4f29ce55517a6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.20820c5463af764170dd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.234dd07f8b4fbcfff1c8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.259d0d3ad3cc625c09cc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.261c547443359b2ed617.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.26c4a820ccdf59a01e12.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.2744526df8f20b22dd63.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.2ba83d12677c8ca8862c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/28e8b98e3dded619c32a0f2b2a14a36cc264d321
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.2c45bd394dc5f874c5e7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.2d6df87cbe9854d27b33.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.2dae51fc3869e9d29c59.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.32e0ceb60fe7d26884ba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.358ce94820cf71781f8a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.3591d6148ca5c82b6492.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.368afc54032341bb7321.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.37f8ebc2f46f9232fd3a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.38ff0644aa8c0926fe90.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.3963d32c5d7c0b86edfa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/2bbbfc0179862ee8792258faa797f6aede35bea0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.39aeb981073e7bfe42c4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.3a988ecb191649a267f1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.3ad194af9b355dca1233.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.3e41b6017b63cedcbd86.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.40175e464ce1b0bfd388.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.417c95caaf847973d02b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d099fd87e78ef1309517326310d9deca839a4822
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.41966229a8d95ddfa733.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.44302e880e5091fef8dd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.44550142e5098b06992f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.450ba8e716c78829ed2f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.45e73ecb70261655f05f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.46facaa9a3f30f5d0f9f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.4bf3a5c43ddad5adc0bd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/33a91173e8d675254fea4178b311890513ddb661
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.4c6e36bc4eefccfc4aa2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.4d903e04e61d5c65b425.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.4ec3a4055cd1567e4f71.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.4f22617bcb49868ad95a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.4fb2eb8246fb30136eab.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.505d7a7c99a1011884cf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.526c7a3b0f38d7f051b6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.536a3ae0d604d56594aa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.548bc1832d671d2270a2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.5512083ca26190a217e4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.566d88afaff985221ff8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.56838d36cfb7086534c1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.57c96e1b73c2406b23df.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.594358088fd41492592b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.5b83bf565915cf727e02.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.5b84c3618f353e817bbd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.5c9bedd7cb1c49ba4d3c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.5d21bdb10a04c2d26943.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.5d44c3b07271fa60b12b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.5d91e1d50c93d2294506.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.5f7b016299612ef20b4d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/a1420ebb34855ee6ab1354615f4ece7d99864ad7
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.6469116e707862868b2f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.65e504096487b3bf65d8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/926b958bd808e895be72c185d2e3e3ef83e72728
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.677797931679bc7a4ce3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.6830049f4057528ec7c6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.6b4f56ddd55b4e94346a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.7090cb104e850bfeb3ce.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ede281ca359aa558c7cc1f9cda6ed8d4155f916b
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.7178bfc10a8f6b2025d3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.732a41329129818669b0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.73d352ef95c1687f2633.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.73eb85d8032e7c1c4781.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/082941a7f02836ab876becf8033d17969077f808
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.758829c9c0831a029f00.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.76494ba6b2faf4600987.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.7688da7a128a2e3e399e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.7893a394928cd97f3a01.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.7a1f640ad8a9c43d0ed9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.7c2ad27c07e3a798f7b6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/296de64c72c469be5dfee20d7634274e21295da2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.7cf53285e89aa47ddedf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.7eada344780435ddfe58.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.7f5fb26b085650af1737.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.800928dee91a73137666.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.8091cb86eb2c2c7c8ba0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.816e03ff8485365362e5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.81d46ffb42f4f35a54dc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.87c97751d88efdc1c064.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.8864123dbc9ff36716ad.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.88c3361931e717b96a29.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.88db725bff6b73fca472.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.8980fecf3707c125fe76.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.8fde3569c0d9769befaf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.90b92b2a87968f5e1e7a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.923b6be6e602263b4207.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.939c275fc2346dac61d7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.99ced535eb2dcc6b73ca.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.a10df75ab590eda0f75e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.a1f0440c53ce0bdb9147.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.a6666ecf1f7ecd9eb454.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62136e24680fe414fc09d780306bdd05a83a7b84
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.a73c5bdb98e81294f4d0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.a773c810e606d68eb28a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.a7af0a1941afcb684772.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fbee7a73a68a619856ed0fc7584febcc4867bf15
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.a7cf417cd8016d18f088.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.a81c21a10073ba29ca3b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.a941bb064359e384327f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9c0205a2ef4453e4cb8d779d41bb610b6e0fd577
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.ab5ad0edb9e50408b82c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.ade591374a5e299a757f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.af72d68f94ef24c2210d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.b3275d63c4ceacee09cc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.b7659e4fbd10a45ccf06.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.b83cdd265f9474ac8671.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.ba419d168818484f86f5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.bb43a2cf5eb5082601bf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0ba74c5f4aee0f52e27c777397602871dc5fbe6
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.bc185876d176ee0fa757.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.bcc5f413400e1e44dfe6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.bfbb2b5ce33df32bae33.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ea68a5af689f6c5b7deb26c906d794cc21b30c5d
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.c27590e986a1a060cea9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.c75403066dd08894ccb6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.cadb148b0c9f09f1c1af.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.cb1982496c1c74f5294f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.cdf299c982313e15dec5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.ce323bc5478e517426e4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.cff6364a38274993dc9b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.d0b15e2d939015153039.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.d1471365008ff765c0d8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.d275a78ceb0f7f82cc0b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.d43ac4e43601aa0d6ce5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.d65e3b54fc1046883cfa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.d78cc60a5a5e19c299da.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.d7a6c24454010eb8d9e7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3e99fe4555b051b96603c274976496d7262b4ca1
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.d8881c2a42559ee62fd2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.d91ccde50563086030e0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.da18fa4f2a1bb9a30554.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.dd3cbae09eec59da0286.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.dd7adacdc498505162de.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.e4f1b0c439eb983834f7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.e59869f5a4bb22ed58d7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.e7cb711e47bedae4d58d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.e879f5dca8939de0f0ae.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.eb4eb7da90caa0289085.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.edcb72b2e1f70ee4211b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.ef6d8bc1dfd55db23430.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/a5da69309bfb05ff3d4b714d5fbeced6a158b577
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.eff5f1cefda7fb89ea65.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f149ba98f9d7e4d70202.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f3b44b4dc27e1d54791b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f4059d6d881987f47c39.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f5922720b1a11747015e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f5e4d3bee2a40de327bb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f6482963762c3948e018.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f727e79f721e147bb7b3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f76e3c55e6f384e0ec22.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f7ac840d4a47969da59c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f8ce6a7164d565eb9124.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.f9e7b4fa48bcc40e80f3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.fa0e2650ecb7eac51320.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.fb62322d89b0243358a5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.fcd6fd9fb6a74099911a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/chunk.ff9194b0bb806d042a72.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210226.0/hass_frontend/frontend_latest/onboarding.cb324e59.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ad1e35077641b30a9415dfe579381bb72cb6f8f4
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/home-assistant-frontend/082941a7f02836ab876becf8033d17969077f808
/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
/usr/share/package-licenses/home-assistant-frontend/1c03cb1c44bce8c770cf95f29b419b2f66b3f1e5
/usr/share/package-licenses/home-assistant-frontend/22ad76b604b952863b489212cd4bd483934a0f91
/usr/share/package-licenses/home-assistant-frontend/25e294a6a0b71f82276a1f5a59dd5419091d78d7
/usr/share/package-licenses/home-assistant-frontend/28e8b98e3dded619c32a0f2b2a14a36cc264d321
/usr/share/package-licenses/home-assistant-frontend/296de64c72c469be5dfee20d7634274e21295da2
/usr/share/package-licenses/home-assistant-frontend/2bbbfc0179862ee8792258faa797f6aede35bea0
/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
/usr/share/package-licenses/home-assistant-frontend/33a91173e8d675254fea4178b311890513ddb661
/usr/share/package-licenses/home-assistant-frontend/3a5e42877be32c2f355e3d5d12f6e9744b02634d
/usr/share/package-licenses/home-assistant-frontend/3e99fe4555b051b96603c274976496d7262b4ca1
/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
/usr/share/package-licenses/home-assistant-frontend/435d3db816faac614d5584fc8df6d09ea9828b3a
/usr/share/package-licenses/home-assistant-frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
/usr/share/package-licenses/home-assistant-frontend/52b17ec5e6f6b2e1b929a94e0bd82be968697e4d
/usr/share/package-licenses/home-assistant-frontend/53304ea17e1aec59135e38fb41046b29226ee4c4
/usr/share/package-licenses/home-assistant-frontend/56d4bbd6d09030f63728cd0c0ca3e4f5cc675ae1
/usr/share/package-licenses/home-assistant-frontend/5f5ceb3bcca2d04378e9be079c358c4df55dd279
/usr/share/package-licenses/home-assistant-frontend/62136e24680fe414fc09d780306bdd05a83a7b84
/usr/share/package-licenses/home-assistant-frontend/69870830409c8dc4d7516131e195dfd5a0ad7b5c
/usr/share/package-licenses/home-assistant-frontend/69b762f663d6f84e74531b04958db753995d73bc
/usr/share/package-licenses/home-assistant-frontend/6c2db91439b31a6213936efdcdc0cac714289755
/usr/share/package-licenses/home-assistant-frontend/7d0116083cabbccafb66a7dc1b7850c35cb691f7
/usr/share/package-licenses/home-assistant-frontend/8221af1259a5d2d0f00c62f1fc77fe1d97a1e2fe
/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
/usr/share/package-licenses/home-assistant-frontend/926b958bd808e895be72c185d2e3e3ef83e72728
/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
/usr/share/package-licenses/home-assistant-frontend/9c0205a2ef4453e4cb8d779d41bb610b6e0fd577
/usr/share/package-licenses/home-assistant-frontend/a1420ebb34855ee6ab1354615f4ece7d99864ad7
/usr/share/package-licenses/home-assistant-frontend/a5da69309bfb05ff3d4b714d5fbeced6a158b577
/usr/share/package-licenses/home-assistant-frontend/abcdbb59740145f8df008f10b6786ec816877d8b
/usr/share/package-licenses/home-assistant-frontend/ad1e35077641b30a9415dfe579381bb72cb6f8f4
/usr/share/package-licenses/home-assistant-frontend/bc3f40e6ed8bcbf1f353f2820b6f6de1b60692aa
/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
/usr/share/package-licenses/home-assistant-frontend/bdfd476700d49e8a2039d45efb2a07fc1ca66016
/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
/usr/share/package-licenses/home-assistant-frontend/d099fd87e78ef1309517326310d9deca839a4822
/usr/share/package-licenses/home-assistant-frontend/d0ba74c5f4aee0f52e27c777397602871dc5fbe6
/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
/usr/share/package-licenses/home-assistant-frontend/dc3e013cd0b737daef34779bfdae382ea163d175
/usr/share/package-licenses/home-assistant-frontend/e52de0b21ae90ae1a028c6551c36eadba3ae7c88
/usr/share/package-licenses/home-assistant-frontend/ea68a5af689f6c5b7deb26c906d794cc21b30c5d
/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
/usr/share/package-licenses/home-assistant-frontend/ede281ca359aa558c7cc1f9cda6ed8d4155f916b
/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
/usr/share/package-licenses/home-assistant-frontend/fbee7a73a68a619856ed0fc7584febcc4867bf15

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
