#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : home-assistant-frontend
Version  : 20210127.3
Release  : 178
URL      : https://files.pythonhosted.org/packages/7a/55/76a8bd6f17f980578930b796988387ccdde9f7fc2379bd3096bbb116eea1/home-assistant-frontend-20210127.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/7a/55/76a8bd6f17f980578930b796988387ccdde9f7fc2379bd3096bbb116eea1/home-assistant-frontend-20210127.3.tar.gz
Summary  : The Home Assistant frontend
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: home-assistant-frontend-license = %{version}-%{release}
Requires: home-assistant-frontend-python = %{version}-%{release}
Requires: home-assistant-frontend-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Home Assistant Frontend
This is the repository for the official [Home Assistant](https://home-assistant.io) frontend.

%package license
Summary: license components for the home-assistant-frontend package.
Group: Default

%description license
license components for the home-assistant-frontend package.


%package python
Summary: python components for the home-assistant-frontend package.
Group: Default
Requires: home-assistant-frontend-python3 = %{version}-%{release}

%description python
python components for the home-assistant-frontend package.


%package python3
Summary: python3 components for the home-assistant-frontend package.
Group: Default
Requires: python3-core
Provides: pypi(home_assistant_frontend)

%description python3
python3 components for the home-assistant-frontend package.


%prep
%setup -q -n home-assistant-frontend-20210127.3
cd %{_builddir}/home-assistant-frontend-20210127.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1611929229
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/home-assistant-frontend
cp %{_builddir}/home-assistant-frontend-20210127.3/LICENSE.md %{buildroot}/usr/share/package-licenses/home-assistant-frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/authorize.d36cfaac.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/00ea2981364df96428b22656ced4c6afce1b8f5c
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.02498d7708948fecbeb0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.030c0f798fb862d59a71.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.055665864c578fd5648f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d099fd87e78ef1309517326310d9deca839a4822
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.061faa607545f099d22b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.062c128defe9d1bfaf42.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.0653475791eaed6c31ed.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.068712510f578eff5abc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.0b6a7a737f60866b0249.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.0cbff8798ef3d8cf9a63.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.0d9cc91ea6ada4bac2c3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.0dc7626b9aa016a11778.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.15832123a748b5c23379.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.171ee984941bd6eab467.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.182b6100714a09b3a449.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.19174ebfcfc35b926264.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.1be03eebeea26cd282e3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.1c7ca3783fd20be2d73e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.1d6728c0ba18839d90e4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.1ea0751f73fd16fc6895.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.207ed61c5c76be2ced62.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.229dd07974d105aa9523.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.236c8889349f40b3161e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.237797f269063d236cbd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.23c07f9fe849538e3bbf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.23ce91e865dafde2ffd5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.26280e8526faa9d5b8d0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.28aa7880dbaac039b2b8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.31314e01ab22baee10d0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.317c6f03fc37f704662b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.31feb41680d59c8bc594.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/52b17ec5e6f6b2e1b929a94e0bd82be968697e4d
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.32248ffc6be6fab71413.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.328dd59c804f7e070b62.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ede281ca359aa558c7cc1f9cda6ed8d4155f916b
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.343162d3cf62f1ae3f37.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.3543e907349401b10310.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.35a99ae78f9d52cada10.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/4a6e6111a58f2215cbccad4e18ab009bcaff1123
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.3ce2ab0bba416bf10148.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/dc3e013cd0b737daef34779bfdae382ea163d175
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.40731387cf098ec097d7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.40d7a0d5aeb89ebd1910.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.459a343ec682ec387022.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.48111c319e9266baf9fc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.48d96600c578df578b51.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.49286f1d62ff700930eb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/5f5ceb3bcca2d04378e9be079c358c4df55dd279
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.493c14693c357f14ec92.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.49a81f9a6b5a184afe58.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.4afa065f0900079fae8b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.4b0745de247aefd6e574.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.4b97afa5f83158d086a2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3e99fe4555b051b96603c274976496d7262b4ca1
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.4bc0a610278a0d001de3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.4ed799ed1339f631b98d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ea68a5af689f6c5b7deb26c906d794cc21b30c5d
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.4fa8a6c85ec37fbee69b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/53304ea17e1aec59135e38fb41046b29226ee4c4
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.50a45dfadd8cb46b50bd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.528e12f4f94c4f42347c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.52bda5e6eef7ab173b87.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.53b16138a660873ad78c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.55a0c9a8fd3ef306d998.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.57f059a0878f0c60f574.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.582b3aed21b23bea4921.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.5bf737ced5ffb26c2715.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.5e6b599e0d18284d210b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.6980948a9820a26c39c9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.6a74f6dd4102e08949aa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.6bd9701868b778b85c65.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.6c43a9977012ae4df9d7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.6cb2a509479780bfeb40.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.6d86f179ce3bfb07cbab.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.6f15cf5a8e074254d023.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.6f99d109641b13404c3f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.7140af9726031a9cac2e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.7347c0f69b74bf72a86e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.77e9db5f62bbee652129.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.7a710a24c1034735352a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.7a71a31e9ad03e12a6c4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.7c47c85d023616785fda.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.801068de282ebb24d723.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.85c37d7970074f7c86e7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.8787d4ecb030ea9b7df7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.879b2d44d6825d49332d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.88ccd230096c1c68775f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.8c71d8e0d248d36660a1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.8ef059b0c3f9a55a3546.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.8f1a2161d85e965663d5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/e52de0b21ae90ae1a028c6551c36eadba3ae7c88
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.8f5f2e5138c11c71c4c0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/56d4bbd6d09030f63728cd0c0ca3e4f5cc675ae1
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.8fd508e2544d6051c808.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.8fdaef564e01bbebc480.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/7322a6c79605414a5559f070f5b44d094ade59ce
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.901696c294d30a9b576b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.92a827c98ed228911aae.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.932bb7867a191addf801.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.9461e942c70636c64d37.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.955ab31f96abed30111b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/81e80451557636132be562e9af7136aeee18075a
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.95d3d269c6a4edac8eaf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.978e9e4992e15c4bd4d4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.9a964cd8b0e452cfcf57.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.9aa0b871b54064e2e0b5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.a01376de93bba50f191b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.a1ac7af4ed6401f0fb02.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.a216f41fda4fa993e5d1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/88e5e2dc82ce282a82aed6818ef05823570ab935
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.a311551f50c4916012fa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.a7e8a495a061240b10b2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.a9336d21a87e22cfbfe4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.adc9f81ac62d12530409.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.ade9408a7c049c5e34e8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/8221af1259a5d2d0f00c62f1fc77fe1d97a1e2fe
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.b5836fae83671e7ed761.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.b8704aba80791f56dcc1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.bfcd0c9471e6d3d017d3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.bfd6d1e219a91d00031b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/52b17ec5e6f6b2e1b929a94e0bd82be968697e4d
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.c030916d72b4e93161ea.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.c041ef221f4184dbbaec.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.c26bc799b785aef370e8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.c413721179564ca81a3f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.c55cc198c55cf261e31a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.c6920826ff494592ea4d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.c732fcdb10ef56d0864b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.c8ab7a5eba9a285117ed.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.ca02652aecb2a990e1e7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.ca3d1afb0109d6c52f49.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.caf399002ac2894cbd81.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.cbbb40b05b4b6a347ab2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.cf40235570c37ae9e7be.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.d43f562ce9c2a91697f9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.d721fff06b0990b542fa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.dae0331a2e33cc5e9079.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.df0dadfcbf32793b18eb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.e0be161bdd87a5e098ac.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.e39ea117c168c549f820.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.e5f52007259956805f75.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.e6b2a9fe3ab16bb7bc5d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.e7ebe3882fbccd42c1ff.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.e91df126061940281d0b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.eacc4cde587159b3a5cf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.eb2b6ead65690929a490.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.ee97619151e3904fa682.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.f2ff89ad8ade8169cbbd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.f3d35c2a4f8127bc1ae2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.f40add69b9bc82c604e0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bdfd476700d49e8a2039d45efb2a07fc1ca66016
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.f4c0baaaf6c8956ceeba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.f7609b93eae6fa12353e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc3f40e6ed8bcbf1f353f2820b6f6de1b60692aa
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.f87c64a89d41a9139f8a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.f91ac88306993d58e3b9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.fb406453f1675b87c1fe.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.fbd644878b06ff4c8cf8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.fc7b4531d94bcc69ef1b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/chunk.fd7940fcee1f82d4cf3c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_es5/onboarding.a9467af9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/25e294a6a0b71f82276a1f5a59dd5419091d78d7
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/app.89f114a4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/1c03cb1c44bce8c770cf95f29b419b2f66b3f1e5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/authorize.8d327f5f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/4822cee9fdbf538d9d1a2fbc4d356105e3f81be4
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.005df8c90cf60bcc4ef7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ea68a5af689f6c5b7deb26c906d794cc21b30c5d
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.0060accace2c6b4b7b61.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.0087a8bb99ee5af8aa54.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/81e80451557636132be562e9af7136aeee18075a
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.034c0fe3fe096de4f1a5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.060d2e2e95d2908720d6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.0647849310089fcdd86f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.080e826950fa2e95b5a0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.085b53e1dea6324707b4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.09eafe5a884c12695685.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.0a0a811dea693e757b4b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.0d5dc53c13211c70c05b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.0ee8efb94ffd88c180ac.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/7322a6c79605414a5559f070f5b44d094ade59ce
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.0ef8d927345fc3a67e6e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.10a16e4ddf47c2e020af.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.1199a3e11ed815ffa618.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.16f567b0fb1e40492118.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.174e838877c574773dc6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.17e91532e58ae6fa4be6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.19203edea035ed52c83c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bdfd476700d49e8a2039d45efb2a07fc1ca66016
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.19c4d1cb6a141499a15d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.1a07b61795b407aa752c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.1b6c2a4c1ec94e6bd3d3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.1e97dfd52656122293ef.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.2172464202cd7a2b8f74.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.22891d4b17025a529817.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.2330c61a541f2fb8da99.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.2381850446194085a2e7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.24febb3ff9ff0b6554de.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.26f9ae56f89ee96382df.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.280dd52ae8fd48b80df4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.289906db4610320b71b3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.2f3926b5ed8e2c056fa1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.307823d4a42a86dba081.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fbee7a73a68a619856ed0fc7584febcc4867bf15
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.31b12554c80980b201c4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/52b17ec5e6f6b2e1b929a94e0bd82be968697e4d
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.331acfadc5436a20c88a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.346bb9a6ebcd9712e09e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.360d3196cd26bdaff0a3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.381ad9fc3ff4beed06be.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.3900ecc4e1ac1f50f585.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.39f5c5bf31882f65d779.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/5c01037b1ffd8e40a4dcdab8c83b3d52ff0c00d5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.3a124d39c4c895833d1c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.3ba6b4bc9644bfa170f2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.3caeb5f6dd611750bec1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.4098dab5d282ba5f37b6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.449237d56758925299b2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.450f2b48ac02232f339e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.467b75e21c6e0423759f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc3f40e6ed8bcbf1f353f2820b6f6de1b60692aa
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.46d188aefa1499458b72.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.4896d23ba163bb85f179.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.4c6704b99bd2cc64b4c4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.4ed871ce23d8e1bfa645.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.4f0be9fab32446f404d9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.4f56526c260e1c6282aa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.5243779d55b7814b3ccf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/abcdbb59740145f8df008f10b6786ec816877d8b
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.528a561f9552876fa059.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.554b6eefceccb7553af9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.5587b72294eb8ed12316.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/435d3db816faac614d5584fc8df6d09ea9828b3a
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.5650e5787d738686ad6a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.584fc08e8cd688d49536.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/8221af1259a5d2d0f00c62f1fc77fe1d97a1e2fe
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.5c8c51aa5b2941e42397.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.5d30c6bd63d1ecefee17.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.5dd40db263d91d834aef.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.64da3012594cac26542e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.662f6e6e0dd1f81757ff.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.671cccf625c3b6fcb0ba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0ba74c5f4aee0f52e27c777397602871dc5fbe6
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.69a2c99fe99493c9478e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.6c605473ef643878ba6b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.6d179f0b1aebbd832ab0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.6de2bed84290c35695ea.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.6f41ea14c9e2296fe370.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.7091ec279a1a2d3cfdc3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.7179ce75d33ece388823.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.7235c3780b2a63a1d2ea.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3e99fe4555b051b96603c274976496d7262b4ca1
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.723bf92ae3e2511e5f1c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.733f4c1fe186fcbe9e4b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.73978ab23c822df9d973.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.751dadace2ac5e7f8137.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.75d4107d30f012428474.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.75f7d290f82547b486aa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/52b17ec5e6f6b2e1b929a94e0bd82be968697e4d
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.7728b6789f318aaf47f4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.778fe3916ed9924ac169.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/2bbbfc0179862ee8792258faa797f6aede35bea0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.7a606a97c83e13e02586.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.7db3d2929ad9a5f79829.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.7f7996a1defec0b70fd4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.80977ab3b8d260aa80f7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.80be83fe4c478540c8ca.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.81994458256fdd682b40.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.8337159ae41450182ea6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.839e95aa23b8cdc66cbf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.84171e32bc9a83aaeda9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/33a91173e8d675254fea4178b311890513ddb661
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.85d7b8cf920c459dfe76.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.87c3c5f0631fcd359c5a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.8a256c53a889a329ad34.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.8ac9ecd802f3489b12f4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/296de64c72c469be5dfee20d7634274e21295da2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.8b4d6f7a0092dc9baa03.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.8b7c13d200037096d385.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.8e0f7317bbe296f16870.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.8f0a4728a6b77d5e33cc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.90d20d3cc70d5fcb97c7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.92849cf20b1d7782f831.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.92b2ebe41572abb2b2d0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.9531d82c59d09a41597e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ede281ca359aa558c7cc1f9cda6ed8d4155f916b
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.979e6fb0cc6da93148fb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.9b646911f7cce171ca93.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.9f891fa7676ac21b6502.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.a1a5203b2a1b90b806b0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.a1af5d72bebe267a0f38.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.a29a27338ed8457b70ec.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.a3a4f41135aeb4c68fed.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.a67ef00f1f55cc846c89.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.a9270fceb8d5b295b6c3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.aa7b6d09bdbef81e08e8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.ab18ddfd51f27de8403c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.abfcdc23f5c686f5d2fc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.ac2bf32cf2c537e98ce2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.ac93c4858dec9fad56a8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.ae123c611b687a809b24.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.af817b88af24be611cf4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.b1611853f62c46fac7ce.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.b2ce5f75a4b1ce36f8c1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.b326b57f498356f791b7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.b3b0215f7342e6b6a0c9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/24134ff6336ee380d1efa3f2c07615e8119a4156
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.b3bc93945e860c4f9859.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.b6d1b00fcd0e18a4ab02.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.b9337f76c078ae8f5a44.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.bd2ec40f82887add70b9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/56d4bbd6d09030f63728cd0c0ca3e4f5cc675ae1
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.bd51308493be1ac46c3c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.be20c02a634c0dfdeeba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.bff99e3c07f870859c58.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.c033b5d4b6c0d44744a3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.c0731d37a4bd768a63b3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.c0ed32e75b99cc1afc44.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.c142d8d3c698e2cc7ae2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.c2243fa0ac9f1afd8b7e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.c3b541ec50220d785393.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.c469d63b2eb7fb706548.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.c7ea1e06e8b22283f8cb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.c9fc9d2e98c76b2dbe6d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.cc707b897e9e9616ac4e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.cda3af98b329b42a3a95.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.d00e717d8e62357f8128.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.d11f8434316451d3a570.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.d22c27f5c8a5903b038f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.d5a618698df587237b8e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.d5e80306ed8a8bf1f984.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d099fd87e78ef1309517326310d9deca839a4822
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.d9a49dde1fcb75ffcfce.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.e6181e962362c22e0505.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/926b958bd808e895be72c185d2e3e3ef83e72728
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.e767fadba242d4da3f89.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.e77d9bf649ffeaffe714.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.ea6804c5168d41dabbe7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.eca4c4a68710363fdcdf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.f1aad416fc318caf8d67.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.f2488b56e14d31fbb3b6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.f3933724c00d923ff446.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.f45a39190544c865a55c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.f6307486a304e6228d4f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.fc74828c2386d4150996.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.fcb56555f0793d37e4de.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/dc3e013cd0b737daef34779bfdae382ea163d175
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.fedf8317f36ed6dd523e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/chunk.ff6d79235b7730a51af8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20210127.3/hass_frontend/frontend_latest/onboarding.4e62ac17.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ad1e35077641b30a9415dfe579381bb72cb6f8f4
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/home-assistant-frontend/00ea2981364df96428b22656ced4c6afce1b8f5c
/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
/usr/share/package-licenses/home-assistant-frontend/1c03cb1c44bce8c770cf95f29b419b2f66b3f1e5
/usr/share/package-licenses/home-assistant-frontend/24134ff6336ee380d1efa3f2c07615e8119a4156
/usr/share/package-licenses/home-assistant-frontend/25e294a6a0b71f82276a1f5a59dd5419091d78d7
/usr/share/package-licenses/home-assistant-frontend/296de64c72c469be5dfee20d7634274e21295da2
/usr/share/package-licenses/home-assistant-frontend/2bbbfc0179862ee8792258faa797f6aede35bea0
/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
/usr/share/package-licenses/home-assistant-frontend/33a91173e8d675254fea4178b311890513ddb661
/usr/share/package-licenses/home-assistant-frontend/3e99fe4555b051b96603c274976496d7262b4ca1
/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
/usr/share/package-licenses/home-assistant-frontend/435d3db816faac614d5584fc8df6d09ea9828b3a
/usr/share/package-licenses/home-assistant-frontend/4822cee9fdbf538d9d1a2fbc4d356105e3f81be4
/usr/share/package-licenses/home-assistant-frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
/usr/share/package-licenses/home-assistant-frontend/4a6e6111a58f2215cbccad4e18ab009bcaff1123
/usr/share/package-licenses/home-assistant-frontend/52b17ec5e6f6b2e1b929a94e0bd82be968697e4d
/usr/share/package-licenses/home-assistant-frontend/53304ea17e1aec59135e38fb41046b29226ee4c4
/usr/share/package-licenses/home-assistant-frontend/56d4bbd6d09030f63728cd0c0ca3e4f5cc675ae1
/usr/share/package-licenses/home-assistant-frontend/5c01037b1ffd8e40a4dcdab8c83b3d52ff0c00d5
/usr/share/package-licenses/home-assistant-frontend/5f5ceb3bcca2d04378e9be079c358c4df55dd279
/usr/share/package-licenses/home-assistant-frontend/7322a6c79605414a5559f070f5b44d094ade59ce
/usr/share/package-licenses/home-assistant-frontend/81e80451557636132be562e9af7136aeee18075a
/usr/share/package-licenses/home-assistant-frontend/8221af1259a5d2d0f00c62f1fc77fe1d97a1e2fe
/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
/usr/share/package-licenses/home-assistant-frontend/88e5e2dc82ce282a82aed6818ef05823570ab935
/usr/share/package-licenses/home-assistant-frontend/926b958bd808e895be72c185d2e3e3ef83e72728
/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
/usr/share/package-licenses/home-assistant-frontend/abcdbb59740145f8df008f10b6786ec816877d8b
/usr/share/package-licenses/home-assistant-frontend/ad1e35077641b30a9415dfe579381bb72cb6f8f4
/usr/share/package-licenses/home-assistant-frontend/bc3f40e6ed8bcbf1f353f2820b6f6de1b60692aa
/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
/usr/share/package-licenses/home-assistant-frontend/bdfd476700d49e8a2039d45efb2a07fc1ca66016
/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
/usr/share/package-licenses/home-assistant-frontend/d099fd87e78ef1309517326310d9deca839a4822
/usr/share/package-licenses/home-assistant-frontend/d0ba74c5f4aee0f52e27c777397602871dc5fbe6
/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
/usr/share/package-licenses/home-assistant-frontend/dc3e013cd0b737daef34779bfdae382ea163d175
/usr/share/package-licenses/home-assistant-frontend/e52de0b21ae90ae1a028c6551c36eadba3ae7c88
/usr/share/package-licenses/home-assistant-frontend/ea68a5af689f6c5b7deb26c906d794cc21b30c5d
/usr/share/package-licenses/home-assistant-frontend/eabc8f90a83cc820e75e2a1faec5be6c3dd4d822
/usr/share/package-licenses/home-assistant-frontend/ede281ca359aa558c7cc1f9cda6ed8d4155f916b
/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
/usr/share/package-licenses/home-assistant-frontend/fbee7a73a68a619856ed0fc7584febcc4867bf15

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
