#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : home-assistant-frontend
Version  : 20200715.1
Release  : 137
URL      : https://files.pythonhosted.org/packages/07/24/567d41c0d8236e825a7d68e7467db7598b1d20f193c41d3973103a5b84b2/home-assistant-frontend-20200715.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/07/24/567d41c0d8236e825a7d68e7467db7598b1d20f193c41d3973103a5b84b2/home-assistant-frontend-20200715.1.tar.gz
Summary  : The Home Assistant frontend
Group    : Development/Tools
License  : Apache-2.0 BSD-3-Clause MIT
Requires: home-assistant-frontend-license = %{version}-%{release}
Requires: home-assistant-frontend-python = %{version}-%{release}
Requires: home-assistant-frontend-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3

%description
# Home Assistant Frontend
This is the repository for the official [Home Assistant](https://home-assistant.io) frontend.

%package license
Summary: license components for the home-assistant-frontend package.
Group: Default

%description license
license components for the home-assistant-frontend package.


%package python
Summary: python components for the home-assistant-frontend package.
Group: Default
Requires: home-assistant-frontend-python3 = %{version}-%{release}

%description python
python components for the home-assistant-frontend package.


%package python3
Summary: python3 components for the home-assistant-frontend package.
Group: Default
Requires: python3-core
Provides: pypi(home_assistant_frontend)

%description python3
python3 components for the home-assistant-frontend package.


%prep
%setup -q -n home-assistant-frontend-20200715.1
cd %{_builddir}/home-assistant-frontend-20200715.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1594924590
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/home-assistant-frontend
cp %{_builddir}/home-assistant-frontend-20200715.1/LICENSE.md %{buildroot}/usr/share/package-licenses/home-assistant-frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/app.5832b6f2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/22d92cb07227ff751a92a83b75c8bca080a14f8d
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/authorize.f2a5a197.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f231c97029cbf63801c72fa1db88455deb05f35a
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.04a2bc608c7cfd029c2f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/a1420ebb34855ee6ab1354615f4ece7d99864ad7
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.0601dd061ae3406e17a2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/8073c6d2d854887d330e7de31f482689a72cc4e8
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.06f41e49e05eb6ce2efa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.09d3215530463f19eb5d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.0b9f6b58cffde85480e1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.0bbd426e1969d037ccc9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.0c02ad5c9e0106e4205a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.10c959f1642df394b4aa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.115d2d9a52e6e86aec35.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.1172c78d32ca92215408.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.137f6f288f768d93178b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.16d2327c755539f02a20.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.1a3e2584908fcac8a4e9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.1accc0571a0264713d2e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.2100e0cb723e1dcfd0b7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.28d690ea44273fb04e29.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.32bcad71aaca7adcc719.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.350b00db31f02548984f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.3be372492c46f7d23329.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.3e882d3148b6dfbdbf8b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.3fe230cee382bdf432cf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.3ff352a459bf6328a14b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.40bc765cb46bd4111ea5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/53304ea17e1aec59135e38fb41046b29226ee4c4
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.42e871696bd46ff97701.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bf1f50eab985089d0ba98b6c1b38c7b113721f52
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.4485f9914b218bcdab94.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62136e24680fe414fc09d780306bdd05a83a7b84
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.44933a28dbb98c819892.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.46bbc7f53d9ac9455041.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/1c4af75c522101485c7b0d4261624755212bcb7b
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.47a6d76554cda45ce951.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/50b474867a8bfae637b9e784a25c55f255c7b7ea
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.490c02b94556f399da4c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.498e21ed4344fea0511b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.49dcd8b9f4f92ef4a5e0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f778af4b9f9d31656cbfa289a9e025bd49f852ca
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.529782699ede17b3fad0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.542d40710470fcec7f6a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/2bbbfc0179862ee8792258faa797f6aede35bea0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.5ca3432d81ce6adc044a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.5ffa3b59649fd5af8f3d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.6037a2758d76a1b95e6e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.60a06beea6fa69ad6c7b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.61297e4603d38b3c465a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.6486ad2a44f9cdb1c1e3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.65e1836821f036214673.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d3afd9bb9e0eec307f379137f72fc96399037d76
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.699e5d076e7172b95f21.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.6a1c154feec72c9f17a1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/7d405a559ba1f2bc6ee293d732b8e946d8e67913
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.6bf8c79582c788591034.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.6cd200e0049658a54be7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.75c99a3059761c0f1690.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.76d9ccf50afe115b1664.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.776e0aaee03d25bd0c57.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.80b7538e299e1e4112e1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.8398af06ada52243ec15.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62c65d7b0577f288dfbb2aeecaa6f2714e4e600e
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.84d263b56bc8e6c74fa0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.86dac788613aa20b0b60.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.87475c8a6ad9601f566f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3e99fe4555b051b96603c274976496d7262b4ca1
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.8e6b6bbbab696161c187.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f86aa7742c11a2ed0be7382ee1c09095c1e1869c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.9606d06bd76038692cfe.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.9611497fd161bff8c593.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.99a7aeb82f14b3a9e6a0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.9c203d676c789a02fd8a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.9f1a390b3118c405fe6c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.a1e165a85a459ecf392a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/6799bbca4ccec236228c075c65642e8259daa222
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.a470923ab01809f50630.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/84710ca6783092702092700cbdbd4b92eadd4864
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.a503e41e597ef2a51861.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.aa36d8f58e0481d06a73.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62c65d7b0577f288dfbb2aeecaa6f2714e4e600e
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.ab5e1a4829e934929b2d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/90dae9cf642bdcbfa7aea93cfdee5d1483483f95
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.abeca69c76222a7cffb1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.ac153fe7b93382d580d3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.ad0d4c3b6fc5f70de931.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/afe7358317fec873e1f291924462ba541c48a3ba
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.b0bfafff8166ad0e5d97.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.b2bbac93cec73335e509.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.b5f5f84d9b6e189ec722.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.b67b5241f03d9fa934bf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/cbf74c0e9140bc047fdb6da1d14315373c8507dc
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.b745a9e96c32c18ec4bb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.b8b3b8a0f5a988a0e011.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/e50765027552371dad5f36bda77ce951dad31936
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.bbef7665ef3318b89bc3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.bc6c67b93aaa3d3f4e10.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.be5b2430dfebcc952873.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.c030e7dd385a6be5edcf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.c24cbd694d9413422122.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.c3a31ea673f300f7d869.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.c4089df8abd92ee77af2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/90dae9cf642bdcbfa7aea93cfdee5d1483483f95
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.c41f8fe9df6eec02a22b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/043dd79d1b51cef3e2e95c7c851aa2d8bbfb9686
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.c8fdf45c2e647cd6e836.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.c9b0994a49bbb523086b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.ca95325d8b642432daef.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.d2f3a20c48672eab0d2a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.d31c9130c5e6bfa2c8c5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/01064b160b1022e3ecf54aefad95d368f347499b
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.d64381a480c10c5290ac.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/01064b160b1022e3ecf54aefad95d368f347499b
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.d857f1aaf3ca9ac2820b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.dbf74206891721edfea6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.de07fb84bce85f1d9a61.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.e244d732ab15d6a85aa8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.e7100e72845bc4c19904.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.e786ce97c95d52d7db71.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.e9fb49cb6ca27dcf1878.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.eb361b217b58adedbd4d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62c65d7b0577f288dfbb2aeecaa6f2714e4e600e
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.eb617ff646c9c2fb2035.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.eb81ce643ccc7058eed1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.eec61c7f4fa5091c58a0.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.f07421da50913828148a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.f0de6aa0c456cb8e1e0b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.f10902de762fe3a8e7f5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.f32ff4237b122328e501.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.f41728e6503a79db8a07.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.f87538a44822b164513d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.f8d1da9e9785571e6605.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/5962264f761d86ef8f5705a25f3af3cd46ae4034
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.f8e79a333fbda056ea7d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.fb744679940da18d362d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.fcd64b5c0da1d17b4c69.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62c65d7b0577f288dfbb2aeecaa6f2714e4e600e
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.fd20442b31d94226e743.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9b152288402cde0c3df4ac0bb7f00c21bef216e7
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/chunk.fefa9c86ca680554622a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_es5/onboarding.25e817ed.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/b0b97a6fd0c8c5eb6b2dacffa7a231a377cb861f
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/app.ebc06441.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/22d92cb07227ff751a92a83b75c8bca080a14f8d
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/authorize.02f42f96.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/b4a071ed7fb801492ed7735330aef877b5461dee
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.025e2e2522d28e34c2ed.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/cbf74c0e9140bc047fdb6da1d14315373c8507dc
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.045e9db0218edca0e0bb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.05afdca5485a5fe1084f.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.08dd1a13511f923f6d5b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.0a30cb3d077169829c29.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.0b5e3ceb2090068f9df6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ec9c4f6e9681176106855bf7302cb6ac11a63729
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.0d5138b987f68946bd32.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.0d608b72d5e040aa3f98.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.0e3786329381fec5598a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62c65d7b0577f288dfbb2aeecaa6f2714e4e600e
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.0e9bc52aa63834977e2b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.129155dcb64ea8c08255.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.140668280ae58a55fabe.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/dcc6d790d8f29d4a901373a3445c4caeff9f4e7f
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.157b4794e00e3272fa5b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/31a83597f4b19e0f7c53870222813f61c3f161e3
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.1bb5abb192d52ba65ab7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.1f907d7ea5a4894a946b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.201b5febf054bc95867a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/2bbbfc0179862ee8792258faa797f6aede35bea0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.22d2e860594982fb8873.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/20d8c518840280151e8e7b35b8e6ac08d69ddc07
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.232ab9b2fe991bf4b970.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.246ac98552fc3de12dd3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/5962264f761d86ef8f5705a25f3af3cd46ae4034
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.252c9ec027082e7d7533.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.258d20b96961030ee7c5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.2719a307202f41255444.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.2c6f67a9851e1fb3e9bf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.2e606d69eb9f629e1759.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.31340d10930f11d14243.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.31f238a86e8412f71462.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/8073c6d2d854887d330e7de31f482689a72cc4e8
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.3416e3b73a929a64bf3c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.3589f26a14b8571b17a3.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/31a83597f4b19e0f7c53870222813f61c3f161e3
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.3b7bf2b589439096b023.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.3c74f20a8b5ae6c404d8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.3d1f1d448e4cbafb1f4a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/ccf4ff985ce68320c239f833e63aa5d4f3b40581
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.42ba10381577cf638d6b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.46a46c4dbd7a45d12064.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.497945aecd21c20e4159.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.49c9ce1dae664fe386cf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.4b6495e3801ab43bd3fa.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.4de117b20acab69ba02b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.5624fa980a6b2ac10526.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/0c3048f071a7f5b6e2034a03318c2069b521ce81
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.582a2968cc36c6302d0b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.5b26b6fc0b99ebd4407e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.5c548db38e5951e62b5b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.5f221db145cb7f931994.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0ba74c5f4aee0f52e27c777397602871dc5fbe6
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.6247177ac9285f21507d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.6390df583558da259018.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.63f6f00c0d2897d65a75.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62c65d7b0577f288dfbb2aeecaa6f2714e4e600e
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.6555825bcf45d4d2da9a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.656f41546257a86cb706.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.69d78e199cc3a8c15114.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.6d80ff6d03c34ec0482d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62c65d7b0577f288dfbb2aeecaa6f2714e4e600e
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.6e4250701c222722c5c7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.6eaa040f2b2c535accf7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/0df7d026608627cd9259304c3c796e182f2e0616
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.6fa4b3720b786314165a.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.77ed0cc0063cbc2c96e4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.7dad09b9c683dbe9ac28.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.7e1d47f39045fbdb6dca.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.7e869e46cf1034145591.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.7ee58d3e9d43618e3219.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.7fb03a7c7c67b1aa5cb5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.819062a4b74e46389b77.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bf1f50eab985089d0ba98b6c1b38c7b113721f52
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.86bafb15c8fc79ac09ea.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.882144219816b092df94.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.8abe9dbc337d882fcd43.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.8b2c0a63fd7a46fc5cfc.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.8c9429cfa2670a888729.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.8f1bb252c75fce86dce1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.90d95041a9ccda6011a2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f26c52990b1ba9d1a3324aed11d19e69c20c62d8
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.9501e20ac07cdb270fe4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.98ff6a782434a54ac0cd.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/62c65d7b0577f288dfbb2aeecaa6f2714e4e600e
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.9be8282daa96eea86c00.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.9ff30e5c5eca15247e18.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.a0d08c05a5f0d756f7a1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.a32f01ad4e55bb868232.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.a88a078d79022b11611d.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/e3f5d41363986b1b94cfee47506ca774a208e0f5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.a8a6b892565600346d41.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/6799bbca4ccec236228c075c65642e8259daa222
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.aa116c033e6b8cf26be7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.aceef46e5993bf9f7daf.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/1f23202d7b34d5e993c290a00bcd7e0284064e77
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.ad1f71a8e9f0e978d666.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.ad21d509f5086295f2d9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3e99fe4555b051b96603c274976496d7262b4ca1
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.ae0b525373b4ee9d6cef.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.ae423b31a86a78d22335.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.b0b048c5cf571f52be70.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.b2bae69a1779e8bfcf65.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.b3c67335bba05f3b78f6.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.b3e67a08660276e361a5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.b41e3e374eab71cc0a13.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.b5e6f3c61c27d6c909be.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.b627b818040cfa977ff5.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/f778af4b9f9d31656cbfa289a9e025bd49f852ca
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.b8511e2cce2bc68285ba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.ba7b94e2dfbe0664b935.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.bd21e8cd4be6f4f63ae9.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.c0f8fe231b59589bd416.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.c3015127bd90a6f67f11.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.c55389a60981cea89eae.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.c6082818907ce8d6c3a2.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.c83f98f91ac5649aff62.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/0c3048f071a7f5b6e2034a03318c2069b521ce81
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.c8539369e7dc4009163c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.cea94322d0a04a38dd10.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.d0ad08439701d909d14b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/84710ca6783092702092700cbdbd4b92eadd4864
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.d1c38c59e7f58ac806a4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.d267c1d4a2fbd5a1d412.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.d56f46194643d85bed2c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.d67529346eb3995e0ea8.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.d833b9e018967a91aee1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.dc4cd6892e7f5a8b5784.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/afe7358317fec873e1f291924462ba541c48a3ba
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.dd8e91ce1089d53aca6b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.e0dffebdba9b5b375b3e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/e50765027552371dad5f36bda77ce951dad31936
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.e4d212eb940d9ac402b1.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.ea7d25ce6bdd232418ba.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.ed135971e6c8cfda4c7c.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.ee56852ea0195977d94e.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.f1f992b1e5160fb09c09.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.f2be3d7a4cff640ec416.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/a1420ebb34855ee6ab1354615f4ece7d99864ad7
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.f2f2279fdb2f6d61766b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.f33d5c8e791a3e2172fb.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.f351a219bbb533b94325.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.f59d46a266f8f36cc744.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.fa3b77724c48af4379c7.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.fda28705520bf38c1439.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/chunk.fefccaaab75676f45fa4.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
cp %{_builddir}/home-assistant-frontend-20200715.1/hass_frontend/frontend_latest/onboarding.9fd7264b.js.LICENSE.txt %{buildroot}/usr/share/package-licenses/home-assistant-frontend/b0b97a6fd0c8c5eb6b2dacffa7a231a377cb861f
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/home-assistant-frontend/01064b160b1022e3ecf54aefad95d368f347499b
/usr/share/package-licenses/home-assistant-frontend/043dd79d1b51cef3e2e95c7c851aa2d8bbfb9686
/usr/share/package-licenses/home-assistant-frontend/0c3048f071a7f5b6e2034a03318c2069b521ce81
/usr/share/package-licenses/home-assistant-frontend/0df7d026608627cd9259304c3c796e182f2e0616
/usr/share/package-licenses/home-assistant-frontend/126c94bc7bdb0095a12ad56ce6975fc7aa445ad5
/usr/share/package-licenses/home-assistant-frontend/1c4af75c522101485c7b0d4261624755212bcb7b
/usr/share/package-licenses/home-assistant-frontend/1f23202d7b34d5e993c290a00bcd7e0284064e77
/usr/share/package-licenses/home-assistant-frontend/20d8c518840280151e8e7b35b8e6ac08d69ddc07
/usr/share/package-licenses/home-assistant-frontend/22d92cb07227ff751a92a83b75c8bca080a14f8d
/usr/share/package-licenses/home-assistant-frontend/2bbbfc0179862ee8792258faa797f6aede35bea0
/usr/share/package-licenses/home-assistant-frontend/30730e4fdc3053671b6092bda9684a55d3299eb5
/usr/share/package-licenses/home-assistant-frontend/31a83597f4b19e0f7c53870222813f61c3f161e3
/usr/share/package-licenses/home-assistant-frontend/3cae19f5070769e50ef113ff476bd29b276f9e97
/usr/share/package-licenses/home-assistant-frontend/3e99fe4555b051b96603c274976496d7262b4ca1
/usr/share/package-licenses/home-assistant-frontend/426cd0438026f00b03fee2f3f2c3f342adf1ef66
/usr/share/package-licenses/home-assistant-frontend/4a606a34022a7ef2eab88e43148dd48547d3c017
/usr/share/package-licenses/home-assistant-frontend/50b474867a8bfae637b9e784a25c55f255c7b7ea
/usr/share/package-licenses/home-assistant-frontend/53304ea17e1aec59135e38fb41046b29226ee4c4
/usr/share/package-licenses/home-assistant-frontend/5962264f761d86ef8f5705a25f3af3cd46ae4034
/usr/share/package-licenses/home-assistant-frontend/62136e24680fe414fc09d780306bdd05a83a7b84
/usr/share/package-licenses/home-assistant-frontend/62c65d7b0577f288dfbb2aeecaa6f2714e4e600e
/usr/share/package-licenses/home-assistant-frontend/6799bbca4ccec236228c075c65642e8259daa222
/usr/share/package-licenses/home-assistant-frontend/7d405a559ba1f2bc6ee293d732b8e946d8e67913
/usr/share/package-licenses/home-assistant-frontend/8073c6d2d854887d330e7de31f482689a72cc4e8
/usr/share/package-licenses/home-assistant-frontend/84710ca6783092702092700cbdbd4b92eadd4864
/usr/share/package-licenses/home-assistant-frontend/87b094c5dfe6598f37df2222986b534be56e0786
/usr/share/package-licenses/home-assistant-frontend/90dae9cf642bdcbfa7aea93cfdee5d1483483f95
/usr/share/package-licenses/home-assistant-frontend/971648e1257541060d2781192eadbbd4b25bbd4f
/usr/share/package-licenses/home-assistant-frontend/9b152288402cde0c3df4ac0bb7f00c21bef216e7
/usr/share/package-licenses/home-assistant-frontend/9f66597010db1afb5e0113ee494948d7b0b52e1c
/usr/share/package-licenses/home-assistant-frontend/a1420ebb34855ee6ab1354615f4ece7d99864ad7
/usr/share/package-licenses/home-assistant-frontend/afe7358317fec873e1f291924462ba541c48a3ba
/usr/share/package-licenses/home-assistant-frontend/b0b97a6fd0c8c5eb6b2dacffa7a231a377cb861f
/usr/share/package-licenses/home-assistant-frontend/b4a071ed7fb801492ed7735330aef877b5461dee
/usr/share/package-licenses/home-assistant-frontend/bc57faaf465e3d0f534c043605a17f39684ffeb0
/usr/share/package-licenses/home-assistant-frontend/bf1f50eab985089d0ba98b6c1b38c7b113721f52
/usr/share/package-licenses/home-assistant-frontend/c6f4a8a5feb0c5734c6d554ff7ab830d45ce5bed
/usr/share/package-licenses/home-assistant-frontend/cbf74c0e9140bc047fdb6da1d14315373c8507dc
/usr/share/package-licenses/home-assistant-frontend/ccf4ff985ce68320c239f833e63aa5d4f3b40581
/usr/share/package-licenses/home-assistant-frontend/d0670e34b874eb9d45b70c95b52f99d3058579d2
/usr/share/package-licenses/home-assistant-frontend/d0ba74c5f4aee0f52e27c777397602871dc5fbe6
/usr/share/package-licenses/home-assistant-frontend/d22c3bf160d8bfeccb275192b6e8154820b8a6c0
/usr/share/package-licenses/home-assistant-frontend/d3afd9bb9e0eec307f379137f72fc96399037d76
/usr/share/package-licenses/home-assistant-frontend/d45cd5d066ba17a3836857b8b6089e2a1c28868c
/usr/share/package-licenses/home-assistant-frontend/dcc6d790d8f29d4a901373a3445c4caeff9f4e7f
/usr/share/package-licenses/home-assistant-frontend/e3f5d41363986b1b94cfee47506ca774a208e0f5
/usr/share/package-licenses/home-assistant-frontend/e50765027552371dad5f36bda77ce951dad31936
/usr/share/package-licenses/home-assistant-frontend/ec9c4f6e9681176106855bf7302cb6ac11a63729
/usr/share/package-licenses/home-assistant-frontend/f12d17e4713167bb7d7334d85cc466402bacff89
/usr/share/package-licenses/home-assistant-frontend/f231c97029cbf63801c72fa1db88455deb05f35a
/usr/share/package-licenses/home-assistant-frontend/f26c52990b1ba9d1a3324aed11d19e69c20c62d8
/usr/share/package-licenses/home-assistant-frontend/f778af4b9f9d31656cbfa289a9e025bd49f852ca
/usr/share/package-licenses/home-assistant-frontend/f86aa7742c11a2ed0be7382ee1c09095c1e1869c
/usr/share/package-licenses/home-assistant-frontend/fb3724a403cfac8a891cbd6be583aaa458459643

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
